### ISSUE TITLE
CTRL-Click on FreePascal units and identifiers

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#17]
When doing CTRL-Click on Classes in the uses clause, it doesn't go to the file.

I have set the path of FPC source correctly in general settings:
**C:\lazarus\fpc\3.0.4\source\**

Is there something else to set up?

**Comment by fredvs** [comment]
Hello.

Did you read the MSE issue?
https://github.com/mse-org/mseide-msegui/issues/3#issuecomment-612637277

**Comment by circular17** [comment]
Oh I see. I forgot about that as it was not in context because we were talking about MSE files.

So if I understand, I need to add directories both in the Make directories and the Debugger directories. Seems redundant to me but not a big deal.

**Comment by fredvs** [comment]
Yes because this are 2 different things.
And how much you add directories in the Search directory list, how more work you ask to the computer.

If you have a fast one, no problem.
But if you add for example in the search list all the directories of fpc source, CTRL+Click will search in all the list and it could take some time.

In the Make directory list, you do not need to add the directories of fpc because it is done by the fpc.cfg.

**Comment by circular17** [comment]
Alright
