### ISSUE TITLE
When compiling the output file is "demo.exe.exe"

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#19]
The EXE extension is added twice.

**Comment by fredvs** [comment]
Please setup the extension in the Project-Option-Make-Exe extension.
It is because ideU is universal and can do poly-compilation (use different compilers from different OS), for example compile with the Wine emulator.

![Capture d’écran_2020-04-17_18-19-38](https://user-images.githubusercontent.com/3421249/79591005-39d87600-80d8-11ea-9ae2-df0dda0319bf.png)

**Comment by fredvs** [comment]
Check also that you dont have added a extension in the Targetfile.
See previous image, the 2 th field in top.

**Comment by fredvs** [comment]
If you should have set in General setting - Other - Default extension:

![Capture d’écran_2020-04-17_18-41-22](https://user-images.githubusercontent.com/3421249/79593036-2549ad00-80db-11ea-9e74-5293bdacd875.png)

**Comment by circular17** [comment]
Oh ok there was the extension in the target file.
