### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by circular17** [fredvs/ideU#30]
For someone interested in ideU, it would help that release page would explain essential installation considerations:

- one need to download MSEgui **source code**
- then to download ideU **source code**
- then to download ideU **binary** and put it in the root of the **source code**
- launch ideU and set up all the paths

**Comment by fredvs** [comment]
OK, I will do.

**Comment by fredvs** [comment]
> For someone interested in ideU, it would help that release page would explain essential installation considerations:
> 
>     * one need to download MSEgui **source code**
> 
>     * then to download ideU **source code**
> 
>     * then to download ideU **binary** and put it in the root of the **source code**
> 
>     * launch ideU and set up all the paths

Sorry but, imho, it is not the right way to do.
I would recommend to:

- If one want to compile MSEgui application, one need to download MSEgui source code.
- then to download ideU `release binary`.
- launch ideU and set up all the paths
- if the one want to compilelast version of ideU, then to download ideU source code.
- When ideu is re-compiled, copy the binary` /src/ideu ` and replace the old binary of `ideU` that is in release directory with the copy of the new one.

This because in release is added all the pluggins that are not in the source.

**Comment by circular17** [comment]
Ok. Well you see I cannot remember how to do it. Better explain it.

**Comment by fredvs** [comment]
Many thanks for your advice.
It is highly appreciated, I dont see all those basic things and it will help new comers.

**Comment by circular17** [comment]
Your explanations are fine. I suggest either to put it in the release description, or to put a link in the release description to a page where this is written.

**Comment by fredvs** [comment]
Ok, some more explanations added here:
https://github.com/fredvs/ideU/releases/tag/2.0.0

**Comment by circular17** [comment]
Perfect !
